# Config file for automatic testing at travis-ci.org

sudo: false

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install tox

# command to run tests, e.g. python setup.py test
script: tox -e $TOX_ENV

after_success:
  # Report coverage results to codecov.io
  - pip install codecov
  - codecov
