# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.7"

env:
  - TOX_ENV=py27
  - TOX_ENV=flake8

# mostly what's needed for the C++ PD test
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install libjudy-dev
  - sudo apt-get install -y libboost-dev libboost-test-dev libboost-program-options-dev libboost-system-dev libboost-filesystem-dev libevent-dev automake libtool flex bison pkg-config g++ libssl-dev
  - wget -c http://archive.apache.org/dist/thrift/0.9.2/thrift-0.9.2.tar.gz && tar -xzvf thrift-0.9.2.tar.gz && cd thrift-0.9.2/ && ./configure && make && sudo make install && cd ..
  - wget http://download.nanomsg.org/nanomsg-0.5-beta.tar.gz && tar -xzvf nanomsg-0.5-beta.tar.gz && cd nanomsg-0.5-beta && ./configure && make && sudo make install && cd ..
  - sudo ldconfig

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install -r requirements.txt
  - pip install tox
  - cd pd_mk/ && ./autogen.sh && ./configure 'P4_PATH=tests/test.p4' 'P4_PREFIX=test' && make all && cd ..

# command to run tests, e.g. python setup.py test
script:
  - tox -e $TOX_ENV
  - cd pd_mk/; make check; cd ..

after_success:
  # Report coverage results to codecov.io
  - pip install codecov
  - codecov
